name: Update README

on:
  push:
  schedule:
    # 每天北京时间早上8点 = UTC 0点
    - cron: '0 0 * * *'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++ && sudo apt-get install -y pandoc

      - name: Compile generate.cpp
        run: g++ seating.cpp -o seating

      - name: Run the program
        run: ./seating

      - name: Replace README.md with out.md and generate PDF
        run: |
          cp seating.md README.md
          pandoc -s README.md -o out.pdf

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update README from generate.cpp output"
            git push
          fi
