name: Auto Generate PDF from Markdown

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # 北京时间早上8点

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Compile generate.cpp
        run: g++ seating.cpp -o seating

      - name: Run generate and save output
        run: ./seating

      - name: Copy to README
        run: cp seating.md README.md

      - uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=output.pdf
            seating.md
            --pdf-engine=xelatex

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md output.pdf
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update README.md and output.pdf"
            git push
          fi
