name: Generate PDF with Typst

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0点 = 北京时间 8点

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile generate.cpp
        run: g++ seating.cpp -o seating

      - name: Run program to generate out.md
        run: ./seating

      - name: Setup Typst CLI
        uses: typst-community/setup-typst@v3

      - name: Convert Markdown to Typst format
        run: |
          echo '#import "typst:preview" #show: document' > out.typ
          echo '' >> out.typ
          cat seating.md >> out.typ

      - name: Generate PDF with Typst
        run: typst compile out.typ output.pdf

      - name: Commit README and PDF
        run: |
          cp seating.md README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md output.pdf
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update README and PDF via Typst"
            git push
          fi
